// 登入、登出
export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// 忘記密碼啦
export const AUTH_FORGOT_START = 'AUTH_FORGOT_START';
export const AUTH_FORGOT_SUCCESS = 'AUTH_FORGOT_SUCCESS';
export const AUTH_FORGOT_FAIL = 'AUTH_FORGOT_FAIL';

export const FETCH_DEVICES_START = 'FETCH_DEVICES_START';
export const FETCH_DEVICES_SUCCESS = 'FETCH_DEVICES_SUCCESS';
export const FETCH_DEVICES_FAIL = 'FETCH_DEVICES_FAIL';
